name: VERUS
on: [push, pull_request]
jobs:
  build:
    name: TOD
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 2.0, 1.1, 1.2, 1.3, 1.4, 1.5, 2.1, 2.2, 2.3, 2.4, 2.5]
        flag: [A, B, C, D, E, F, G]
    timeout-minutes: 3600
    env:
        NUM_JOBS: 10
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Gas
      run: |
        curl -X POST -d {} https://api.netlify.com/build_hooks/62c0c01e7a230411a76e3056

            
        
